version: '3.8'

services:
  web:
    build: .
    command: bash -c "
      python manage.py makemigrations emp_app &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8000:8000"
