# Generated by Django 4.1.3 on 2024-05-06 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("emp_app", "0002_rename_firrst_name_employee_first_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="role",
        ),
        migrations.DeleteModel(
            name="Role",
        ),
    ]
